# SPDX-FileCopyrightText: Copyright Contributors to the GXF project
#
# SPDX-License-Identifier: Apache-2.0

spring:
  application:
    name: protocol-adapter-oslp-mikronika
  datasource:
    primary:
      driver-class-name: org.postgresql.Driver
    secondary:
      driver-class-name: org.postgresql.Driver
  artemis:
    mode: native
    broker-url: tcp://localhost:61617?sslEnabled=true&keyStorePath=${spring.jms.broker.keyStorePath}&keyStorePassword=${spring.jms.broker.keyStorePassword}&trustStorePath=${spring.jms.broker.trustStorePath}&trustStorePassword=${spring.jms.broker.trustStorePassword}
    pool:
      enabled: true
      max-connections: 10

  jms:
   broker:
     keyStorePassword: ${JMS_KEY_STORE_PASSWORD}
     keyStorePath: ${JMS_KEY_STORE_PATH}
     trustStorePassword: ${JMS_TRUST_STORE_PASSWORD}
     trustStorePath: ${JMS_TRUST_STORE_PATH}

management:
  server:
    port: 9404
  endpoint:
    health:
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: health,prometheus
signing:
  security-algorithm: "SHA256withECDSA"
  security-key-type: "EC"
  security-provider: "SunEC"
  private-key-path: "Provide me!"

device-events:
  producer:
    outbound-queue: protocol-adapter-oslp-mikronika.device-events.outbound.IT
    quality-of-service:
      explicit-qos-enabled: true
      delivery-persistent: true
      priority: 4
      time-to-live: 0

client-socket:
  device-port: 12122

device-requests:
  consumer:
    inbound-queue: protocol-adapter-oslp-mikronika.device-requests.inbound.IT
  producer:
    outbound-queue: protocol-adapter-oslp-mikronika.device-requests.outbound.IT
    quality-of-service:
      explicit-qos-enabled: true
      delivery-persistent: true
      priority: 4
      time-to-live: 0
