spring:
  artemis:
    broker-url: tcp://localhost:61616
    user: artemis
    password: artemis
  datasource:
    primary:
      jdbcUrl: jdbc:postgresql://localhost:51360/osgp_adapter_protocol_oslp_mikronika
      username: osp_admin
      password: test
      driver-class-name: org.postgresql.Driver
    secondary:
      jdbcUrl: jdbc:postgresql://localhost:51360/osgp_core
      username: osgp_core_db_api_user
      password: test
      driver-class-name: org.postgresql.Driver

  dev-tools:
    restart:
      enabled: true

  flyway:
    baseline-on-migrate: true

  jpa:
    show-sql: false

server-socket:
  port: 12126
  hostName: localhost
