spring:
  application:
    name: protocol-adapter-oslp-mikronika
  datasource:
    primary:
      driver-class-name: org.postgresql.Driver
    secondary:
      driver-class-name: org.postgresql.Driver

management:
  server:
    port: 9404
  endpoint:
    health:
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: health,prometheus
signing:
  security-algorithm: "SHA256withECDSA"
  security-key-type: "EC"
  security-provider: "SunEC"
  private-key-path: "Provide me!"

device-events:
  enabled: true
  producer:
    outbound-queue: protocol-adapter-oslp-mikronika.device-events.outbound.IT
    quality-of-service:
      explicit-qos-enabled: true
      delivery-persistent: true
      priority: 4
      time-to-live: 0
