# SPDX-FileCopyrightText: Copyright Contributors to the GXF project
#
# SPDX-License-Identifier: Apache-2.0

spring:
  application:
    name: protocol-adapter-oslp-mikronika
  artemis:
    mode: native
    broker-url: tcp://localhost:61616
    user: artemis
    password: artemis
    pool:
      enabled: true
      max-connections: 2
  flyway:
    baseline-on-migrate: true
  main:
    allow-bean-definition-overriding: true

management:
  server:
    port: 9404
  endpoint:
    health:
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: health,prometheus

signing:
  security-algorithm: "SHA256withECDSA"
  security-key-type: "EC"
  security-provider: "SunEC"
  private-key-path: "Provide me!"

device-events:
  producer:
    outbound-queue: gxf.publiclighting.oslp-mikronika.device-events
    quality-of-service:
      explicit-qos-enabled: true
      delivery-persistent: true
      priority: 4
      time-to-live: 0

commands:
  consumer:
    inbound-queue: gxf.publiclighting.oslp-mikronika.device-requests
    min-concurrency: 1
    max-concurrency: 5
  producer:
    outbound-queue: gxf.publiclighting.oslp-mikronika.device-responses
    quality-of-service:
      explicit-qos-enabled: true
      delivery-persistent: true
      priority: 4
      time-to-live: 0

audit-logging:
  producer:
    outbound-queue: gxf.publiclighting.oslp-mikronika.audit-log
    quality-of-service:
      explicit-qos-enabled: true
      delivery-persistent: true
      priority: 4
      time-to-live: 0

server-socket:
  port: 12126
  hostName: localhost

client-socket:
  device-port: 12122
